<?xml version="1.0"?>

<robot name="simple_bot" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:property name="base_width" value="0.2" />
    <xacro:property name="base_length" value="0.8" />
    <xacro:property name="base_height" value="0.4" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_width" value="0.04" />

    <link name="base_link">
        <inertial>
            <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
            <mass value="1"/>
            <inertia ixx="0.5" ixy="0.0" ixz="0.0" iyy="0.5" iyz="0.0" izz="0.5"/>
        </inertial>
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
        </collision>
    </link>

    <link name="right_wheel_link">
        <inertial>
            <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
            <mass value="1"/>
            <inertia ixx="0.5" ixy="0.0" ixz="0.0" iyy="0.5" iyz="0.0" izz="0.5"/>
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
            <material name="Gray">
                <color rgba="0.5 0.5 0.5 1.0" />
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
        </collision>
    </link>

    <joint name="right_wheel_link_joint" type="prismatic">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="-0.2 ${(base_width/2) + (wheel_radius/2)} 0" rpy="0 0 0" />
        <axis xyz="1 0 0" />
        <limit velocity="1" effort="1" lower="-0.4" upper="0.04" />
    </joint>

    <link name="left_wheel_link">
        <inertial>
            <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
            <mass value="1"/>
            <inertia ixx="0.5" ixy="0.0" ixz="0.0" iyy="0.5" iyz="0.0" izz="0.5"/>
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
            <material name="Gray">
                <color rgba="0.5 0.5 0.5 1.0" />
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
        </collision>
    </link>

    <joint name="left_wheel_link_joint" type="fixed">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="0.2 ${(base_width/2) + (wheel_radius/2)} 0" rpy="0 0 0" />
    </joint>
</robot>